# Generated by Django 4.1.7 on 2023-04-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall',
            name='date_de_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
