# Generated by Django 4.1.7 on 2023-03-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recall',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recall',
            name='reference_fiche',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
