# Generated by Django 4.1.7 on 2023-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0002_recall_id_alter_recall_reference_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall',
            name='date_de_publication',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='recall',
            name='lien_vers_affichette_pdf',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='recall',
            name='lien_vers_la_fiche_rappel',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='recall',
            name='motif_du_rappel',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='recall',
            name='ndeg_de_version',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='recall',
            name='nom_de_la_marque_du_produit',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='recall',
            name='noms_des_modeles_ou_references',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='recall',
            name='rappelguid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='recall',
            name='risques_encourus_par_le_consommateur',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
