# Generated by Django 4.1.7 on 2023-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0003_alter_recall_date_de_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall',
            name='categorie_de_produit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='conditionnements',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='conduites_a_tenir_par_le_consommateur',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='date_de_fin_de_la_procedure_de_rappel',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='date_de_publication',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='date_debut_fin_de_commercialisation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='description_complementaire_du_risque',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='distributeurs',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='identification_des_produits',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='informations_complementaires',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='informations_complementaires_publiques',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='lien_vers_affichette_pdf',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='lien_vers_la_fiche_rappel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='lien_vers_la_liste_des_distributeurs',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='lien_vers_la_liste_des_produits',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='liens_vers_les_images',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='marque_de_salubrite',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='modalites_de_compensation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='motif_du_rappel',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='nature_juridique_du_rappel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='ndeg_de_version',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='nom_de_la_marque_du_produit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='noms_des_modeles_ou_references',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='numero_de_contact',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='preconisations_sanitaires',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='rappelguid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='risques_encourus_par_le_consommateur',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='sous_categorie_de_produit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='temperature_de_conservation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='zone_geographique_de_vente',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
