# Generated by Django 4.1.7 on 2023-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0004_alter_recall_categorie_de_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recall',
            name='id',
        ),
        migrations.AlterField(
            model_name='recall',
            name='reference_fiche',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
