# Generated by Django 4.1.7 on 2023-03-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0005_remove_recall_id_alter_recall_reference_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
