# Generated by Django 4.1.7 on 2023-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0006_alter_recall_created_at_alter_recall_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recall',
            options={'ordering': ['-date_de_publication']},
        ),
        migrations.AddField(
            model_name='recall',
            name='ean',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
