# Generated by Django 4.1.7 on 2023-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0007_alter_recall_options_recall_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall',
            name='conditionnements',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='conduites_a_tenir_par_le_consommateur',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='description_complementaire_du_risque',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='distributeurs',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='identification_des_produits',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='informations_complementaires',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='informations_complementaires_publiques',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='liens_vers_les_images',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='marque_de_salubrite',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='motif_du_rappel',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='nom_de_la_marque_du_produit',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='noms_des_modeles_ou_references',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='preconisations_sanitaires',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='risques_encourus_par_le_consommateur',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recall',
            name='zone_geographique_de_vente',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
