# Generated by Django 4.1.7 on 2023-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_du_produit_rayon', models.CharField(max_length=64)),
                ('cause_de_la_demande_de_derogation', models.CharField(max_length=32)),
                ('code_barre_ean_gtin', models.CharField(max_length=32)),
                ('conditionnement', models.CharField(max_length=512)),
                ('denomination_du_produit', models.CharField(max_length=512)),
                ('impact_allergenes', models.CharField(blank=True, max_length=1, null=True)),
                ('marque', models.CharField(max_length=512)),
                ('modalites_d_information_des_consommateurs', models.CharField(max_length=1024)),
                ('nature_du_decalage_entre_le_produit_et_son_etiquetage', models.CharField(max_length=2048)),
                ('datedepot', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-datedepot'],
            },
        ),
    ]
