# Generated by Django 4.1.7 on 2023-03-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('reference_fiche', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('categorie_du_produit_rayon', models.TextField()),
                ('cause_de_la_demande_de_derogation', models.TextField()),
                ('code_barre_ean_gtin', models.TextField()),
                ('conditionnement', models.TextField()),
                ('denomination_du_produit', models.TextField()),
                ('impact_allergenes', models.TextField(blank=True, null=True)),
                ('marque', models.TextField()),
                ('modalites_d_information_des_consommateurs', models.TextField()),
                ('nature_du_decalage_entre_le_produit_et_son_etiquetage', models.TextField()),
                ('datedepot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-datedepot'],
            },
        ),
    ]
