# Generated by Django 4.1.7 on 2023-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensation',
            name='conditionnement',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='denomination_du_produit',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='marque',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='modalites_d_information_des_consommateurs',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='nature_du_decalage_entre_le_produit_et_son_etiquetage',
            field=models.TextField(max_length=2048),
        ),
    ]
