# Generated by Django 4.1.7 on 2023-03-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispensations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensation',
            old_name='reference_fiche',
            new_name='hash',
        ),
    ]
