# Generated by Django 4.1.7 on 2023-04-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensations', '0002_rename_reference_fiche_dispensation_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensation',
            name='datedepot',
            field=models.DateField(),
        ),
    ]
