# Generated by Django 4.1.7 on 2023-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensations', '0002_alter_dispensation_categorie_du_produit_rayon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensation',
            name='datedepot',
            field=models.TextField(),
        ),
    ]
