# Generated by Django 4.1.7 on 2023-03-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='code',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
