# Generated by Django 4.1.7 on 2023-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecallCount',
            fields=[
                ('category', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('recall_count', models.IntegerField()),
                ('product_count', models.IntegerField()),
                ('recall_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-recall_rate', '-recall_count', '-product_count'],
            },
        ),
    ]
