# Generated by Django 4.1.7 on 2023-03-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recallsCounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecallCount',
            new_name='RecallsCount',
        ),
    ]
