# Generated by Django 4.1.7 on 2023-03-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recallsCounts', '0002_rename_recallcount_recallscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recallscount',
            options={'ordering': ['-recall_count']},
        ),
        migrations.RemoveField(
            model_name='recallscount',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='recallscount',
            name='recall_rate',
        ),
    ]
