# Generated by Django 4.1.7 on 2023-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recallsCounts', '0003_alter_recallscount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recallscount',
            name='recall_category',
            field=models.JSONField(default=list),
        ),
    ]
