# Generated by Django 4.1.7 on 2023-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recallsCounts', '0004_recallscount_recall_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recallscount',
            name='recall_rate',
            field=models.FloatField(null=True),
        ),
    ]
