# Generated by Django 4.1.7 on 2023-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispensationsCount',
            fields=[
                ('hash', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=128)),
                ('dispensation_category', models.JSONField(default=list)),
                ('dispensation_count', models.IntegerField()),
                ('dispensation_rate', models.FloatField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-dispensation_count'],
            },
        ),
    ]
