# Generated by Django 4.1.7 on 2023-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensationsCounts', '0002_alter_dispensationscount_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensationscount',
            name='dispensation_allergens_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispensationscount',
            name='dispensation_allergens_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dispensationscount',
            name='dispensation_count',
            field=models.IntegerField(default=0),
        ),
    ]
