# Generated by Django 4.1.7 on 2023-04-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_products_delete_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='mp_eco_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mp_global_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mp_nutrim_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='mp_sanit_score',
            field=models.FloatField(null=True),
        ),
    ]
