# Generated by Django 4.1.7 on 2023-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'brands', 'ean', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.AddField(
            model_name='product',
            name='additives',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='eco_score',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='from_places',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_places',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mp_nutrim_score',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mp_sanit_score',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nova_group',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutri_score',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutriments',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='traces',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vegan',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamins',
            field=models.JSONField(null=True),
        ),
    ]
