# Generated by Django 4.1.7 on 2023-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vegetarian',
            field=models.BooleanField(null=True),
        ),
    ]
