# Generated by Django 4.1.7 on 2023-03-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_labels_product_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='traces',
            field=models.JSONField(null=True),
        ),
    ]
