# Generated by Django 4.1.7 on 2023-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_allergens_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='from_places',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturing_places',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.JSONField(null=True),
        ),
    ]
