# Generated by Django 4.1.7 on 2023-03-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_from_places_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='from_places',
            new_name='factories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='carbon_footprint',
            new_name='mp_eco_score',
        ),
    ]
