# Generated by Django 4.1.7 on 2023-03-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_from_places_product_factories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mp_eco_score',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mp_nutrim_score',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mp_sanit_score',
            field=models.JSONField(null=True),
        ),
    ]
