# Generated by Django 4.1.7 on 2023-04-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_ean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='eco_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nova_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutri_score',
        ),
    ]
